server:
  image: sjoerdmulder/teamcity
  ports:
    - 8111:8111
  volumes:
    - /data/teamcity-storage:/var/lib/teamcity
agent:
  image: sjoerdmulder/teamcity-agent
  links:
    - server
  environment:
    TEAMCITY_SERVER: http://server:8111
